"""oauth_tokens_youtube_account_id

Revision ID: 0c7bd3507b14
Revises: a1b2c3d4e5f6
Create Date: 2026-06-14 20:44:26.099134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c7bd3507b14'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_account_id', sa.String(), nullable=True))
        batch_op.alter_column('channel_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('youtube_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_youtube_accounts_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youtube_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_youtube_accounts_workspace_id'))

    with op.batch_alter_table('oauth_tokens', schema=None) as batch_op:
        batch_op.alter_column('channel_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('youtube_account_id')

    # ### end Alembic commands ###
