"""Sprint 7A-5 Metadata Variant Library

Revision ID: 233666a353ae
Revises: 6761f8c23b2b
Create Date: 2026-06-09 20:18:45.639820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '233666a353ae'
down_revision: Union[str, None] = '6761f8c23b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_variants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('package_generation_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_combo', sa.String(), nullable=True),
    sa.Column('source_context', sa.String(), nullable=True),
    sa.Column('is_selected', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metadata_variants', schema=None) as batch_op:
        batch_op.create_index('idx_metadata_variants_package_generation', ['package_generation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metadata_variants', schema=None) as batch_op:
        batch_op.drop_index('idx_metadata_variants_package_generation')

    op.drop_table('metadata_variants')
    # ### end Alembic commands ###
