"""sprint_7b_2_global_prompt_library

Revision ID: 4211f22be9e0
Revises: c31f1d53e2c6
Create Date: 2026-06-10 18:06:44.026489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4211f22be9e0'
down_revision: Union[str, None] = 'c31f1d53e2c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_prompt_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('prompt_id', sa.String(), nullable=False),
    sa.Column('assignment_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'prompt_id', name='uq_channel_prompt')
    )
    with op.batch_alter_table('channel_prompt_assignments', schema=None) as batch_op:
        batch_op.create_index('idx_channel_prompt_assignments_channel_id', ['channel_id'], unique=False)

    with op.batch_alter_table('prompt_contexts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_type', sa.String(), nullable=False, server_default='metadata'))

    # Data Migration: Generate channel_prompt_assignments for existing prompt_contexts
    import uuid
    from datetime import datetime
    connection = op.get_bind()
    results = connection.execute(sa.text("SELECT id, channel_id FROM prompt_contexts")).fetchall()
    
    for row in results:
        assignment_id = str(uuid.uuid4())
        connection.execute(
            sa.text(
                "INSERT INTO channel_prompt_assignments (id, channel_id, prompt_id, assignment_order, is_active, created_at, updated_at) "
                "VALUES (:id, :channel_id, :prompt_id, 1, 1, :now, :now)"
            ),
            {
                "id": assignment_id,
                "channel_id": row[1],
                "prompt_id": row[0],
                "now": datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')
            }
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_contexts', schema=None) as batch_op:
        batch_op.drop_column('prompt_type')

    with op.batch_alter_table('channel_prompt_assignments', schema=None) as batch_op:
        batch_op.drop_index('idx_channel_prompt_assignments_channel_id')

    op.drop_table('channel_prompt_assignments')
    # ### end Alembic commands ###
