"""add_youtube_analytics_and_insights_tables

Revision ID: 53245d76fea0
Revises: ed2a02c8af7e
Create Date: 2026-06-13 14:00:48.875218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53245d76fea0'
down_revision: Union[str, None] = 'ed2a02c8af7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_channel_identities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analytics_channel_id', sa.String(), nullable=False),
    sa.Column('identity_reference_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analytics_channels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('external_channel_id', sa.String(), nullable=False),
    sa.Column('channel_name', sa.String(), nullable=False),
    sa.Column('channel_handle', sa.String(), nullable=True),
    sa.Column('is_own', sa.Boolean(), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_channel_id')
    )
    op.create_table('analytics_insights',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analytics_channel_id', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('insight_type', sa.String(), nullable=False),
    sa.Column('insight_version', sa.Integer(), nullable=True),
    sa.Column('payload_version', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analytics_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('metric_source', sa.String(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('watch_time', sa.Float(), nullable=True),
    sa.Column('subscribers', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('retention_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analytics_videos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('external_video_id', sa.String(), nullable=False),
    sa.Column('analytics_channel_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analytics_workspace_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('analytics_channel_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('google_trends_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('query_term', sa.String(), nullable=False),
    sa.Column('geo', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('interest_value', sa.Integer(), nullable=True),
    sa.Column('related_queries_json', sa.Text(), nullable=True),
    sa.Column('related_topics_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('google_trends_snapshots')
    op.drop_table('analytics_workspace_links')
    op.drop_table('analytics_videos')
    op.drop_table('analytics_snapshots')
    op.drop_table('analytics_insights')
    op.drop_table('analytics_channels')
    op.drop_table('analytics_channel_identities')
    # ### end Alembic commands ###
