"""add_system_settings_and_generation_models

Revision ID: 65b27d5eb8d8
Revises: d44af0502be3
Create Date: 2026-06-12 17:38:37.988216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65b27d5eb8d8'
down_revision: Union[str, None] = 'd44af0502be3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###

    # Seed initial system settings
    system_settings_table = sa.table(
        'system_settings',
        sa.column('key', sa.String),
        sa.column('value', sa.String)
    )
    op.bulk_insert(system_settings_table, [
        {"key": "single_model_endpoint", "value": "http://localhost:20128/v1/images/generations"},
        {"key": "single_model_api_key", "value": ""}
    ])
    
    # Seed initial models
    generation_models_table = sa.table(
        'generation_models',
        sa.column('id', sa.String),
        sa.column('name', sa.String),
        sa.column('is_active', sa.Integer)
    )
    op.bulk_insert(generation_models_table, [
        {"id": "flux-klein", "name": "FLUX.2 Klein 9B", "is_active": 1},
        {"id": "sdxl-10", "name": "SDXL 1.0", "is_active": 1},
        {"id": "flux-schnell", "name": "Flux Schnell", "is_active": 1},
        {"id": "flux-dev", "name": "Flux Dev", "is_active": 1}
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    op.drop_table('generation_models')
    # ### end Alembic commands ###
