"""Sprint 7A-4.7: Generation Audit Foundation

Revision ID: 6761f8c23b2b
Revises: a6871d79b05f
Create Date: 2026-06-09 11:42:36.634360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6761f8c23b2b'
down_revision: Union[str, None] = 'a6871d79b05f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_generations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata_combo_used', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_combo_used', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('prompt_context_used', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_generations', schema=None) as batch_op:
        batch_op.drop_column('prompt_context_used')
        batch_op.drop_column('thumbnail_combo_used')
        batch_op.drop_column('metadata_combo_used')

    # ### end Alembic commands ###
