"""add_archived_and_duration_to_analytics_channel

Revision ID: 8a27d57f0d1b
Revises: 96f332997446
Create Date: 2026-06-13 22:21:39.979839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a27d57f0d1b'
down_revision: Union[str, None] = '96f332997446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics_channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('last_sync_duration_seconds', sa.Integer(), nullable=True))

    with op.batch_alter_table('companion_runtimes', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companion_runtimes', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('analytics_channels', schema=None) as batch_op:
        batch_op.drop_column('last_sync_duration_seconds')
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
