"""sprint_7a_7_asset_variant_library

Revision ID: bb3a638a6fb2
Revises: 93aeedb8341e
Create Date: 2026-06-09 22:54:17.873123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb3a638a6fb2'
down_revision: Union[str, None] = '93aeedb8341e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_selected', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_assets', schema=None) as batch_op:
        batch_op.drop_column('is_selected')

    # ### end Alembic commands ###
