"""create channel upload preferences table

Revision ID: c7a78f2d5b19
Revises: 01844a73643c
Create Date: 2026-06-16 10:38:00.552944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a78f2d5b19'
down_revision: Union[str, None] = '01844a73643c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_upload_preferences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('privacy_status', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('default_language', sa.String(), nullable=True),
    sa.Column('default_tags_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    with op.batch_alter_table('analytics_channel_profiles', schema=None) as batch_op:
        batch_op.drop_index('idx_analytics_channel_profiles_account_id')
        batch_op.create_index('idx_analytics_channel_profiles_account_id', ['youtube_account_id'], unique=False)

    with op.batch_alter_table('analytics_generated_drafts', schema=None) as batch_op:
        batch_op.drop_index('idx_analytics_generated_drafts_enriched')
        batch_op.drop_index('idx_analytics_generated_drafts_workspace')

    with op.batch_alter_table('analytics_insights', schema=None) as batch_op:
        batch_op.drop_index('idx_analytics_insights_fingerprint')

    with op.batch_alter_table('research_context_records', schema=None) as batch_op:
        batch_op.drop_index('idx_research_context_source')
        batch_op.drop_index('idx_research_context_workspace')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_context_records', schema=None) as batch_op:
        batch_op.create_index('idx_research_context_workspace', ['workspace_id'], unique=False)
        batch_op.create_index('idx_research_context_source', ['source_type', 'source_reference_id'], unique=False)

    with op.batch_alter_table('analytics_insights', schema=None) as batch_op:
        batch_op.create_index('idx_analytics_insights_fingerprint', ['fingerprint'], unique=False)

    with op.batch_alter_table('analytics_generated_drafts', schema=None) as batch_op:
        batch_op.create_index('idx_analytics_generated_drafts_workspace', ['workspace_id'], unique=False)
        batch_op.create_index('idx_analytics_generated_drafts_enriched', ['source_enriched_context_id'], unique=False)

    with op.batch_alter_table('analytics_channel_profiles', schema=None) as batch_op:
        batch_op.drop_index('idx_analytics_channel_profiles_account_id')
        batch_op.create_index('idx_analytics_channel_profiles_account_id', ['youtube_account_id'], unique=1)

    op.drop_table('channel_upload_preferences')
    # ### end Alembic commands ###
