"""adjust_connector_models_for_global

Revision ID: d44af0502be3
Revises: 233cad05abbb
Create Date: 2026-06-12 12:28:12.403715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd44af0502be3'
down_revision: Union[str, None] = '233cad05abbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_inbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('metadata', sa.Text(), nullable=True))
        batch_op.drop_column('project_id')

    with op.batch_alter_table('connector_jobs', schema=None) as batch_op:
        batch_op.drop_column('project_id')
        batch_op.drop_column('prompt')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connector_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('project_id', sa.VARCHAR(), nullable=False))

    with op.batch_alter_table('asset_inbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('metadata')
        batch_op.drop_column('source_id')

    # ### end Alembic commands ###
