"""sprint_7c_1_runtime_audits

Revision ID: dbad2e8585c1
Revises: 4211f22be9e0
Create Date: 2026-06-10 19:56:42.954790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbad2e8585c1'
down_revision: Union[str, None] = '4211f22be9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runtime_audits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('execution_id', sa.String(), nullable=False),
    sa.Column('package_id', sa.String(), nullable=False),
    sa.Column('execution_type', sa.String(), nullable=False),
    sa.Column('selected_prompt_id', sa.String(), nullable=True),
    sa.Column('selected_prompt_title', sa.String(), nullable=True),
    sa.Column('assigned_prompt_ids', sa.JSON(), nullable=True),
    sa.Column('assigned_prompt_titles', sa.JSON(), nullable=True),
    sa.Column('prompt_preview', sa.String(length=1000), nullable=True),
    sa.Column('combo_used', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runtime_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runtime_audits_execution_id'), ['execution_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_runtime_audits_package_id'), ['package_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runtime_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runtime_audits_package_id'))
        batch_op.drop_index(batch_op.f('ix_runtime_audits_execution_id'))

    op.drop_table('runtime_audits')
    # ### end Alembic commands ###
