"""create_analytics_generated_drafts_table

Revision ID: ff36ca058386
Revises: 38112bdcc95a
Create Date: 2026-06-14 13:51:34.867167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff36ca058386'
down_revision: Union[str, None] = '38112bdcc95a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_generated_drafts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_export_id', sa.String(), nullable=False),
    sa.Column('source_enriched_context_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('draft_type', sa.String(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('context_version', sa.String(), nullable=False),
    sa.Column('draft_version', sa.String(), nullable=False),
    sa.Column('generated_by', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analytics_generated_drafts')
    # ### end Alembic commands ###
