from typing import Dict, Any

def render_enriched_context_markdown(payload: Dict[str, Any]) -> str:
    """
    Renders Enriched Context payload into human-readable Markdown format
    by dispatching to the appropriate versioned renderer.
    """
    context_version = payload.get("context_version", "2.0")
    enrichment_version = payload.get("enrichment_version", "1.0")

    # Future-proof version routing
    if context_version == "2.0" and enrichment_version == "1.0":
        return render_enriched_context_markdown_v2(payload)
    
    return render_enriched_context_markdown_v2(payload)

def render_enriched_context_markdown_v2(payload: Dict[str, Any]) -> str:
    """
    v2.0 Enrichment Renderer (Research Report)
    """
    topic_name = payload.get("topic_name", "Unknown Topic")
    generated_by = payload.get("generated_by", "unknown")
    enrichment_ver = payload.get("enrichment_version", "1.0")
    
    research = payload.get("research_context", {})
    audience = payload.get("audience_context", {})
    competitor = payload.get("competitor_context", {})
    keywords = payload.get("keyword_expansion", {})
    topics = payload.get("topic_expansion", {})
    intent = payload.get("search_intent_context", {})
    signals = payload.get("market_signals", {})
    
    md = []
    md.append(f"# Research Report: {topic_name}")
    md.append(f"*Generated By: {generated_by} (Enrichment Logic Version: {enrichment_ver})*\n")
    
    # 1. Research & Provenance
    md.append("## 📝 Research & Provenance")
    md.append("### Notes")
    for note in research.get("research_notes", []):
        md.append(f"- {note}")
    if not research.get("research_notes"):
        md.append("- No research notes compiled.")
        
    md.append("\n### Supporting Facts")
    for fact in research.get("supporting_facts", []):
        md.append(f"- {fact}")
    if not research.get("supporting_facts"):
        md.append("- No supporting facts compiled.")
        
    md.append("\n### Related Entities")
    for entity in research.get("related_entities", []):
        md.append(f"- {entity}")
    if not research.get("related_entities"):
        md.append("- No related entities identified.")
    md.append("")
    
    # 2. Audience Understanding
    md.append("## 👥 Audience Understanding")
    md.append(f"- **Target Skill Level:** {audience.get('audience_level', 'Intermediate')}\n")
    
    md.append("### Pain Points")
    for pp in audience.get("pain_points", []):
        md.append(f"- {pp}")
    if not audience.get("pain_points"):
        md.append("- None identified.")
    md.append("")
    
    md.append("### Goals")
    for g in audience.get("goals", []):
        md.append(f"- {g}")
    if not audience.get("goals"):
        md.append("- None identified.")
    md.append("")
    
    md.append("### Common Questions")
    for q in audience.get("common_questions", []):
        md.append(f"- {q}")
    if not audience.get("common_questions"):
        md.append("- None identified.")
    md.append("")
    
    # 3. Competitor Analysis
    md.append("## ⚔️ Competitor Analysis")
    md.append("### Oversaturated Topics")
    for ot in competitor.get("oversaturated_topics", []):
        md.append(f"- {ot}")
    if not competitor.get("oversaturated_topics"):
        md.append("- None identified.")
    md.append("")
    
    md.append("### Undercovered Topics")
    for ut in competitor.get("undercovered_topics", []):
        md.append(f"- {ut}")
    if not competitor.get("undercovered_topics"):
        md.append("- None identified.")
    md.append("")
    
    md.append("### Content Gaps")
    for cg in competitor.get("content_gaps", []):
        md.append(f"- {cg}")
    if not competitor.get("content_gaps"):
        md.append("- None identified.")
    md.append("")
    
    # 4. Keyword Expansion
    md.append("## 🔑 Keyword Expansion")
    md.append("### Primary Keywords")
    for pk in keywords.get("primary_keywords", []):
        md.append(f"- {pk}")
    if not keywords.get("primary_keywords"):
        md.append("- None identified.")
    md.append("")
    
    md.append("### Secondary Keywords")
    for sk in keywords.get("secondary_keywords", []):
        md.append(f"- {sk}")
    if not keywords.get("secondary_keywords"):
        md.append("- None identified.")
    md.append("")
    
    md.append("### Related Keywords")
    for rk in keywords.get("related_keywords", []):
        md.append(f"- {rk}")
    if not keywords.get("related_keywords"):
        md.append("- None identified.")
    md.append("")
    
    # 5. Topic Expansion
    md.append("## 📁 Topic Expansion")
    md.append("### Related Topics")
    for rt in topics.get("related_topics", []):
        md.append(f"- {rt}")
    if not topics.get("related_topics"):
        md.append("- None identified.")
    md.append("")
    
    md.append("### Adjacent Topics")
    for at in topics.get("adjacent_topics", []):
        md.append(f"- {at}")
    if not topics.get("adjacent_topics"):
        md.append("- None identified.")
    md.append("")
    
    md.append("### Semantic Clusters")
    for sc in topics.get("semantic_clusters", []):
        md.append(f"- {sc}")
    if not topics.get("semantic_clusters"):
        md.append("- None identified.")
    md.append("")
    
    # 6. Search Intent Analysis
    md.append("## 🎯 Search Intent Analysis")
    md.append("### Informational Queries")
    for inf in intent.get("informational", []):
        md.append(f"- {inf}")
    if not intent.get("informational"):
        md.append("- None identified.")
    md.append("")
    
    md.append("### Comparative Queries")
    for comp in intent.get("comparative", []):
        md.append(f"- {comp}")
    if not intent.get("comparative"):
        md.append("- None identified.")
    md.append("")
    
    md.append("### Transactional Queries")
    for trans in intent.get("transactional", []):
        md.append(f"- {trans}")
    if not intent.get("transactional"):
        md.append("- None identified.")
    md.append("")
    
    md.append("### Navigational Queries")
    for nav in intent.get("navigational", []):
        md.append(f"- {nav}")
    if not intent.get("navigational"):
        md.append("- None identified.")
    md.append("")
    
    # 7. Market Signals
    md.append("## 📊 Market Signals")
    md.append(f"- **Demand Score:** {signals.get('demand_score', 0.0):.1f}")
    md.append(f"- **Competition Score:** {signals.get('competition_score', 0.0):.1f}")
    md.append(f"- **Forecast Score:** {signals.get('forecast_score', 0.0):.1f}")
    md.append(f"- **Opportunity Score:** {signals.get('opportunity_score', 0.0):.1f}")
    
    return "\n".join(md).strip()

