from typing import Dict, Any

def render_enriched_context_markdown(payload: Dict[str, Any]) -> str:
    """
    Renders Enriched Context payload into human-readable Markdown format
    by dispatching to the appropriate versioned renderer.
    """
    context_version = payload.get("context_version", "2.0")
    enrichment_version = payload.get("enrichment_version", "1.0")

    # Future-proof version routing
    if context_version == "2.0" and enrichment_version == "1.0":
        return render_enriched_context_markdown_v1(payload)
    
    # Fallback to current renderer
    return render_enriched_context_markdown_v1(payload)

def render_enriched_context_markdown_v1(payload: Dict[str, Any]) -> str:
    """
    v1.0 Enrichment Renderer (for Context v2.0)
    """
    topic_name = payload.get("topic_name", "Unknown Topic")
    generated_by = payload.get("generated_by", "unknown")
    enrichment_ver = payload.get("enrichment_version", "1.0")
    
    recs = payload.get("recommendations", {})
    research = payload.get("research_context", {})
    audience = payload.get("audience_context", {})
    competitor = payload.get("competitor_context", {})
    angles = payload.get("angle_candidates", [])
    hooks = payload.get("hook_candidates", [])
    outlines = payload.get("outline_candidates", [])
    
    md = []
    md.append(f"# Enriched Context: {topic_name}")
    md.append(f"*Generated By: {generated_by} (Enrichment Logic Version: {enrichment_ver})*\n")
    
    md.append("## 🎯 Recommendations")
    md.append(f"- **Best Angle:** {recs.get('best_angle', 'N/A')}")
    md.append(f"- **Best Hook:** {recs.get('best_hook', 'N/A')}")
    md.append(f"- **Recommended Video Length:** {recs.get('recommended_video_length', 'N/A')}")
    md.append(f"- **Target Audience:** {recs.get('recommended_audience', 'N/A')}")
    md.append(f"- **Confidence Score:** {recs.get('confidence_score', 0)}%\n")
    
    md.append("## 📝 Research & Provenance")
    md.append(research.get("research_notes", "No research notes compiled."))
    md.append("\n**Sources Analyzed:**")
    sources = research.get("research_sources", [])
    for s in sources:
        md.append(f"- {s}")
    md.append("")
    
    md.append("## 👥 Audience Understanding")
    md.append(f"- **Target Skill Level:** {audience.get('audience_level', 'Intermediate')}\n")
    
    md.append("### Pain Points")
    for pp in audience.get("pain_points", []):
        md.append(f"- {pp}")
    md.append("")
    
    md.append("### Goals")
    for g in audience.get("goals", []):
        md.append(f"- {g}")
    md.append("")
    
    md.append("### Common Questions")
    for q in audience.get("common_questions", []):
        md.append(f"- {q}")
    md.append("")
    
    md.append("## ⚔️ Competitor Analysis")
    md.append("### Oversaturated Topics")
    for ot in competitor.get("oversaturated_topics", []):
        md.append(f"- {ot}")
    md.append("")
    
    md.append("### Undercovered Topics")
    for ut in competitor.get("undercovered_topics", []):
        md.append(f"- {ut}")
    md.append("")
    
    md.append("### Content Gaps")
    for cg in competitor.get("content_gaps", []):
        md.append(f"- {cg}")
    md.append("")
    
    md.append("## 📐 Content Angles")
    for angle in angles:
        md.append(f"- {angle}")
    md.append("")
    
    md.append("## 🧲 Hook Candidates")
    for hook in hooks:
        md.append(f"- {hook}")
    md.append("")
    
    md.append("## 📋 Outline Suggestions")
    for segment in outlines:
        md.append(f"### {segment.get('segment', 'Unknown Segment')} ({segment.get('duration', '0:00')})")
        md.append(segment.get("description", ""))
        md.append("")
        
    return "\n".join(md).strip()
