import uuid
import json
import requests
from datetime import datetime
from typing import Dict, Any, Optional
from sqlalchemy.orm import Session
from fastapi import HTTPException

from database.models import ResearchContextRecord, AnalyticsGeneratedDraft
from app.config import settings
from services.runtime_core_service import sanitize_9router_payload
from services.analytics.angle_generator import generate_angles
from services.analytics.hook_generator import generate_hooks
from services.analytics.outline_generator import generate_outlines

def _build_9router_url() -> str:
    """Build the normalised 9Router /v1/chat/completions URL from settings."""
    base = settings.NINE_ROUTER_URL.rstrip("/")
    if not base.endswith("/v1"):
        base = f"{base}/v1"
    return f"{base}/chat/completions"

def _generate_fallback_draft(topic: str, enriched: ResearchContextRecord) -> str:
    """
    Constructs a highly structured fallback markdown draft.
    Generates Hooks, Angles, and Outlines dynamically in E-3.
    """
    primary_kws = enriched.keywords.get("primary_keywords", [topic])
    angles = generate_angles(topic, primary_kws)
    hooks = generate_hooks(topic, primary_kws)
    outlines = generate_outlines(topic, primary_kws)
    
    best_angle = angles[2] if len(angles) > 2 else angles[0]
    best_hook = hooks[0] if hooks else "Modern hook"
    
    audience = enriched.audience
    competitor = enriched.competitors

    md = []
    md.append(f"# Fallback YouTube Long-form Script: {topic}")
    md.append(f"*Generated by rule-based heuristic draft builder*")
    md.append("")
    md.append("## 📌 STRATEGY SUMMARY")
    md.append(f"- **Best Angle:** {best_angle}")
    md.append(f"- **Best Hook:** {best_hook}")
    md.append(f"- **Recommended Video Length:** 10-15 minutes")
    md.append(f"- **Target Audience:** {audience.get('audience_level', 'General')} Audience")
    md.append("")
    md.append("## 👥 AUDIENCE DETAILS")
    md.append(f"- **Skill Level:** {audience.get('audience_level', 'Intermediate')}")
    md.append("### Target Pain Points")
    for p in audience.get("pain_points", []):
        md.append(f"- {p}")
    md.append("### Goals")
    for g in audience.get("goals", []):
        md.append(f"- {g}")
    md.append("")
    md.append("## ⚔️ COMPETITIVE ADVANTAGE & GAPS")
    md.append("### Content Gaps to Capitalize On")
    for gap in competitor.get("content_gaps", []):
        md.append(f"- {gap}")
    md.append("### Oversaturated Areas (Avoid)")
    for sat in competitor.get("oversaturated_topics", []):
        md.append(f"- {sat}")
    md.append("")
    md.append("## 🎤 VISUAL OUTLINE & SCRIPT SEGMENTS")
    for seg in outlines:
        md.append(f"### Segment: {seg.get('segment', 'Intro')} ({seg.get('duration', '0:00')})")
        md.append(f"**Visual Cue/Direction:** {seg.get('description', '')}")
        md.append("")
        md.append(f"**Narrative Draft:**")
        md.append(f"> \"Welcome back! Today we are looking at {topic}. We know the biggest hurdle is {audience.get('pain_points', ['this problem'])[0]}...\"")
        md.append("")
    return "\n".join(md)

def generate_draft(db: Session, enriched_context_id: str) -> Dict[str, Any]:
    """
    Orchestrates draft generation from the specified Research Context record.
    Uses 9Router chat completion with a structured system prompt, falling back
    to rule-based generation if LLM is unavailable or fails.
    """
    enriched = db.query(ResearchContextRecord).filter(
        ResearchContextRecord.id == enriched_context_id,
        ResearchContextRecord.status == "ready"
    ).first()
    
    if not enriched:
        raise HTTPException(status_code=404, detail="Research context record not found or not in 'ready' status")
    
    topic = enriched.topic or "Unknown Topic"
    
    draft_id = str(uuid.uuid4())
    
    # Create the draft record initially as draft
    draft_record = AnalyticsGeneratedDraft(
        id=draft_id,
        source_export_id=enriched.export_id,
        source_enriched_context_id=enriched_context_id,
        workspace_id=enriched.workspace_id,
        channel_id=enriched.channel_id,
        youtube_account_id=enriched.youtube_account_id,
        title=f"Draft: {topic}",
        draft_type="youtube_longform",
        content_markdown="",
        context_version="2.0",
        draft_version="1.0",
        generated_by="heuristic",
        status="draft",
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow()
    )
    db.add(draft_record)
    db.commit()

    try:
        content_markdown = ""
        generated_by = "heuristic"

        if settings.NINE_ROUTER_URL and settings.NINE_ROUTER_API_KEY:
            try:
                system_prompt = (
                    "You are a master scriptwriter and content creator for YouTube long-form content. "
                    "Analyze the provided Research Context dataset including keywords, audience insights, competitor analysis, search intent, and market signals. "
                    "Based on this research, determine the best hook, target angle, and video structure outline. "
                    "Then, draft a comprehensive, highly engaging, and complete video script draft in Markdown format. "
                    "Include visual directions, detailed outline segments matching timestamps, and fully written narration. "
                    "Do NOT write placeholders (e.g. '[Insert visual here]', '[Explain details here]'). "
                    "Write actual narrative content. Do not wrap response in a json block, return plain Markdown."
                )
                
                # Natively serialize the model properties to build the prompt context
                prompt_context = {
                    "topic": enriched.topic,
                    "trend_score": enriched.trend_score,
                    "keyword_count": enriched.keyword_count,
                    "competitor_count": enriched.competitor_count,
                    "signal_count": enriched.signal_count,
                    "keywords": enriched.keywords,
                    "audience": enriched.audience,
                    "competitors": enriched.competitors,
                    "opportunities": enriched.opportunities,
                    "signals": enriched.signals
                }
                user_message = f"Research Dataset Context:\n{json.dumps(prompt_context, indent=2)}"

                headers = {
                    "Authorization": f"Bearer {settings.NINE_ROUTER_API_KEY}",
                    "Content-Type": "application/json",
                }

                req_payload = {
                    "model": settings.NINE_ROUTER_MODEL or "YT_Research",
                    "stream": False,
                    "messages": [
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_message}
                    ]
                }

                sanitized, timeout_sec = sanitize_9router_payload(db, req_payload)

                response = requests.post(
                    _build_9router_url(),
                    json=sanitized,
                    headers=headers,
                    timeout=timeout_sec
                )
                response.raise_for_status()

                raw_content = response.json().get("choices", [{}])[0].get("message", {}).get("content", "").strip()
                if raw_content:
                    content_markdown = raw_content
                    generated_by = settings.NINE_ROUTER_MODEL or "9router"

            except Exception as llm_err:
                print(f"[Draft Warning] LLM draft generation failed: {llm_err}. Falling back to Rule-based.")

        if not content_markdown:
            content_markdown = _generate_fallback_draft(topic, enriched)
            generated_by = "heuristic"

        # Update draft record
        draft_record.content_markdown = content_markdown
        draft_record.generated_by = generated_by
        draft_record.status = "draft"  # Set to draft once generation complete
        draft_record.updated_at = datetime.utcnow()
        db.commit()
        db.refresh(draft_record)

        # Convert to response dictionary
        return {
            "id": draft_record.id,
            "source_export_id": draft_record.source_export_id,
            "source_enriched_context_id": draft_record.source_enriched_context_id,
            "workspace_id": draft_record.workspace_id,
            "channel_id": draft_record.channel_id,
            "youtube_account_id": draft_record.youtube_account_id,
            "title": draft_record.title,
            "draft_type": draft_record.draft_type,
            "content_markdown": draft_record.content_markdown,
            "context_version": draft_record.context_version,
            "draft_version": draft_record.draft_version,
            "generated_by": draft_record.generated_by,
            "status": draft_record.status,
            "created_at": draft_record.created_at,
            "updated_at": draft_record.updated_at
        }

    except Exception as exc:
        db.rollback()
        failed_draft = db.query(AnalyticsGeneratedDraft).filter(AnalyticsGeneratedDraft.id == draft_id).first()
        if failed_draft:
            failed_draft.status = "deleted"
            db.commit()
        raise HTTPException(status_code=500, detail=f"Draft generation failed: {str(exc)}")
